version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: job_db
      POSTGRES_USER: nguyenbin
      POSTGRES_PASSWORD: 09012003a
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
